const products = [
  {
    id: 1,
    name: "Double Serum Complete Age Control Concentrate",
    brand: "Clarins",
    category: "Skincare",
    price: 89000,
    originalPrice: 105000,
    description: "Clarins' iconic anti-ageing serum powered by 21 plant extracts. Targets all 5 vital functions of the skin.",
    rating: 4.9,
    reviews: 1820,
    stock: "in",
    badge: "Best Seller",
    size: "50ml",
    skinType: "All skin types",
  },
  {
    id: 2,
    name: "Hydra-Essentiel Silky Moisturiser",
    brand: "Clarins",
    category: "Skincare",
    price: 52000,
    originalPrice: null,
    description: "Lightweight silky cream with double hyaluronic acid that quenches skin's thirst instantly and locks in moisture all day.",
    rating: 4.7,
    reviews: 934,
    stock: "in",
    badge: null,
    size: "50ml",
    skinType: "Normal to dry skin",
  },
  {
    id: 3,
    name: "Super Restorative Day Cream",
    brand: "Clarins",
    category: "Skincare",
    price: 98000,
    originalPrice: 115000,
    description: "Award-winning anti-ageing day cream powered by organic harungana — nature's retinol. Firms, lifts and restores radiance.",
    rating: 4.8,
    reviews: 671,
    stock: "in",
    badge: "Award Winner",
    size: "50ml",
    skinType: "All skin types",
  },
  {
    id: 4,
    name: "Blue Orchid Face Treatment Oil",
    brand: "Clarins",
    category: "Skincare",
    price: 67000,
    originalPrice: null,
    description: "100% pure plant extract facial oil that tones, revitalises and restores radiance. Prevents moisture loss.",
    rating: 4.8,
    reviews: 512,
    stock: "in",
    badge: "Iconic",
    size: "30ml",
    skinType: "Dehydrated skin",
  },
  {
    id: 5,
    name: "Multi-Active Brightening Glow Serum",
    brand: "Clarins",
    category: "Skincare",
    price: 74000,
    originalPrice: null,
    description: "Brightening glow serum with plant extracts that visibly evens skin tone and gives skin a radiant, lit-from-within glow.",
    rating: 4.6,
    reviews: 1869,
    stock: "in",
    badge: null,
    size: "30ml",
    skinType: "All skin types",
  },
  {
    id: 6,
    name: "Beauty Flash Balm",
    brand: "Clarins",
    category: "Skincare",
    price: 48000,
    originalPrice: 58000,
    description: "Instant radiance booster that acts like a professional facial in a jar. Visibly reduces signs of fatigue.",
    rating: 4.7,
    reviews: 445,
    stock: "in",
    badge: "Cult Classic",
    size: "50ml",
    skinType: "All skin types",
  },
  {
    id: 7,
    name: "Total Eye Lift Cream",
    brand: "Clarins",
    category: "Skincare",
    price: 61000,
    originalPrice: null,
    description: "All-in-one anti-ageing eye cream that lifts, firms and smooths the eye contour. Reduces crow's feet and dark circles.",
    rating: 4.6,
    reviews: 388,
    stock: "in",
    badge: null,
    size: "15ml",
    skinType: "All skin types",
  },
  {
    id: 8,
    name: "One-Step Gentle Exfoliating Cleanser",
    brand: "Clarins",
    category: "Skincare",
    price: 38000,
    originalPrice: null,
    description: "Two-in-one gentle exfoliating cleanser. Cleanses, exfoliates and tones in one effortless step.",
    rating: 4.5,
    reviews: 302,
    stock: "in",
    badge: null,
    size: "125ml",
    skinType: "All skin types",
  },
  {
    id: 9,
    name: "Clarins Precious La Crème",
    brand: "Clarins",
    category: "Skincare",
    price: 245000,
    originalPrice: null,
    description: "Ultra-luxury anti-ageing cream with rare Moonlight Flower cryoextract for exceptional skin regeneration.",
    rating: 4.9,
    reviews: 124,
    stock: "low",
    badge: "Luxury",
    size: "50ml",
    skinType: "Mature skin",
  },
  {
    id: 10,
    name: "Everlasting Youth Fluid Foundation",
    brand: "Clarins",
    category: "Makeup",
    price: 55000,
    originalPrice: 65000,
    description: "Anti-ageing liquid foundation developed like skincare. Medium coverage with a firm, plump and radiant finish.",
    rating: 4.6,
    reviews: 756,
    stock: "in",
    badge: "New Formula",
    size: "30ml",
    skinType: "All skin types",
  },
  {
    id: 11,
    name: "Lip Comfort Oil",
    brand: "Clarins",
    category: "Makeup",
    price: 27000,
    originalPrice: null,
    description: "The original lip oil that started a worldwide trend. Nourishes and visibly plumps lips. Sold every 8 seconds worldwide.",
    rating: 4.8,
    reviews: 3241,
    stock: "in",
    badge: "Global #1",
    size: "7ml",
    skinType: null,
  },
  {
    id: 12,
    name: "Lip Perfector Peptide-Plumping Gloss",
    brand: "Clarins",
    category: "Makeup",
    price: 32000,
    originalPrice: null,
    description: "Peptide-powered plumping lip gloss that visibly increases lip volume over time. Non-sticky finish.",
    rating: 4.6,
    reviews: 2367,
    stock: "in",
    badge: null,
    size: "12ml",
    skinType: null,
  },
  {
    id: 13,
    name: "Instant Smooth Perfecting Touch Primer",
    brand: "Clarins",
    category: "Makeup",
    price: 42000,
    originalPrice: null,
    description: "Ultra-smooth makeup primer that fills fine lines, smooths pores and creates a flawless base.",
    rating: 4.6,
    reviews: 542,
    stock: "in",
    badge: null,
    size: "15ml",
    skinType: "All skin types",
  },
  {
    id: 14,
    name: "Joli Rouge Moisturising Lipstick",
    brand: "Clarins",
    category: "Makeup",
    price: 30000,
    originalPrice: 36000,
    description: "Moisturising lipstick in a classic satin finish. Intense, long-wearing colour with a comfortable feel.",
    rating: 4.7,
    reviews: 890,
    stock: "in",
    badge: "Sale",
    size: "3.5g",
    skinType: null,
  },
  {
    id: 15,
    name: "Skin Illusion Glow Skin Tint SPF15",
    brand: "Clarins",
    category: "Makeup",
    price: 47000,
    originalPrice: null,
    description: "Glow-boosting skin tint with built-in age-defying skincare and SPF15. 10 versatile shades.",
    rating: 4.5,
    reviews: 412,
    stock: "in",
    badge: "New",
    size: "30ml",
    skinType: "All skin types",
  },
  {
    id: 16,
    name: "Instant Eye Make-Up Remover",
    brand: "Clarins",
    category: "Makeup",
    price: 25000,
    originalPrice: 30000,
    description: "Bi-phase eye make-up remover that gently dissolves even waterproof mascara. Soothes the delicate eye area.",
    rating: 4.8,
    reviews: 678,
    stock: "in",
    badge: null,
    size: "125ml",
    skinType: null,
  },
  {
    id: 17,
    name: "Eau Dynamisante Treatment Fragrance",
    brand: "Clarins",
    category: "Fragrance",
    price: 72000,
    originalPrice: null,
    description: "The world's first treatment fragrance. Hydrates, revitalises and perfumes skin with aromatic essential oils.",
    rating: 4.8,
    reviews: 987,
    stock: "in",
    badge: "Since 1987",
    size: "100ml",
    skinType: null,
  },
  {
    id: 18,
    name: "Eau de Jardins Treatment Fragrance",
    brand: "Clarins",
    category: "Fragrance",
    price: 65000,
    originalPrice: null,
    description: "A fresh, floral treatment fragrance that soothes the senses and nourishes skin with plant extracts.",
    rating: 4.6,
    reviews: 312,
    stock: "in",
    badge: null,
    size: "100ml",
    skinType: null,
  },
  {
    id: 19,
    name: "Eau Ressourçante Treatment Fragrance",
    brand: "Clarins",
    category: "Fragrance",
    price: 65000,
    originalPrice: 75000,
    description: "A calming, restorative treatment fragrance. Warm, oriental scent with skin-caring properties.",
    rating: 4.5,
    reviews: 198,
    stock: "low",
    badge: null,
    size: "100ml",
    skinType: null,
  },
  {
    id: 20,
    name: "Body Treatment Oil — Tonic",
    brand: "Clarins",
    category: "Body",
    price: 78000,
    originalPrice: null,
    description: "Toning body treatment oil with 100% plant extracts that firms, tones and improves skin elasticity.",
    rating: 4.8,
    reviews: 1102,
    stock: "in",
    badge: "Best Seller",
    size: "100ml",
    skinType: null,
  },
  {
    id: 21,
    name: "Body-Smoothing Moisture Milk",
    brand: "Clarins",
    category: "Body",
    price: 42000,
    originalPrice: 52000,
    description: "Lightweight body milk with aloe vera that melts instantly into skin. Silky smooth and lightly scented.",
    rating: 4.6,
    reviews: 445,
    stock: "in",
    badge: null,
    size: "400ml",
    skinType: null,
  },
  {
    id: 22,
    name: "Hand & Nail Treatment Cream",
    brand: "Clarins",
    category: "Body",
    price: 22000,
    originalPrice: null,
    description: "Clarins' iconic hand cream that strengthens nails and deeply nourishes hands. Fast-absorbing formula.",
    rating: 4.9,
    reviews: 2103,
    stock: "in",
    badge: "Iconic",
    size: "100ml",
    skinType: null,
  },
  {
    id: 23,
    name: "Extra-Firming Body Lotion",
    brand: "Clarins",
    category: "Body",
    price: 58000,
    originalPrice: null,
    description: "Firming body lotion that visibly tightens and tones skin. Improves elasticity and leaves skin firm.",
    rating: 4.7,
    reviews: 334,
    stock: "in",
    badge: null,
    size: "200ml",
    skinType: null,
  },
  {
    id: 24,
    name: "Relax Bath & Shower Concentrate",
    brand: "Clarins",
    category: "Body",
    price: 35000,
    originalPrice: 42000,
    description: "Aromatherapy bath and shower concentrate. Relaxes mind and body, leaving skin delicately scented.",
    rating: 4.7,
    reviews: 267,
    stock: "in",
    badge: null,
    size: "200ml",
    skinType: null,
  },
  {
    id: 25,
    name: "ClarinsMen Super Moisture Balm",
    brand: "ClarinsMen",
    category: "Men",
    price: 38000,
    originalPrice: 48000,
    description: "Ultra-hydrating moisturiser for men that soothes skin after shaving. Lightweight gel-balm.",
    rating: 4.6,
    reviews: 412,
    stock: "in",
    badge: null,
    size: "50ml",
    skinType: "All skin types",
  },
  {
    id: 26,
    name: "ClarinsMen Anti-Fatigue Eye Serum",
    brand: "ClarinsMen",
    category: "Men",
    price: 45000,
    originalPrice: null,
    description: "Powerful eye serum for men that reduces dark circles, puffiness and signs of fatigue instantly.",
    rating: 4.5,
    reviews: 198,
    stock: "in",
    badge: null,
    size: "20ml",
    skinType: null,
  },
  {
    id: 27,
    name: "ClarinsMen Exfoliating Cleanser",
    brand: "ClarinsMen",
    category: "Men",
    price: 29000,
    originalPrice: null,
    description: "Deep-cleansing exfoliating face wash with bamboo and pumice particles. Removes impurities and unclogs pores.",
    rating: 4.4,
    reviews: 155,
    stock: "in",
    badge: null,
    size: "125ml",
    skinType: "Normal to oily skin",
  },
  {
    id: 28,
    name: "ClarinsMen Anti-Ageing Eye Cream",
    brand: "ClarinsMen",
    category: "Men",
    price: 52000,
    originalPrice: 62000,
    description: "All-in-one anti-ageing eye cream for men. Reduces crow's feet and dark circles for a younger look.",
    rating: 4.7,
    reviews: 223,
    stock: "low",
    badge: null,
    size: "20ml",
    skinType: null,
  },
  {
    id: 29,
    name: "ClarinsMen Shave Ease Two-In-One Oil",
    brand: "ClarinsMen",
    category: "Men",
    price: 32000,
    originalPrice: null,
    description: "Two-in-one shaving oil that softens beard hair and protects skin for a close, irritation-free shave.",
    rating: 4.5,
    reviews: 178,
    stock: "in",
    badge: null,
    size: "30ml",
    skinType: null,
  },
  {
    id: 30,
    name: "ClarinsMen Multi-Protective SPF20 Moisturiser",
    brand: "ClarinsMen",
    category: "Men",
    price: 41000,
    originalPrice: null,
    description: "Daily moisturiser for men with SPF20. Hydrates, soothes and shields from UV rays all day long.",
    rating: 4.6,
    reviews: 289,
    stock: "in",
    badge: "SPF20",
    size: "50ml",
    skinType: "All skin types",
  },
  {
    id: 31,
    name: "My Clarins Re-Boost Hydra-Gel",
    brand: "My Clarins",
    category: "Skincare",
    price: 36000,
    originalPrice: null,
    description: "Vegan hydrating gel cream for young skin aged 18–29. Light texture, big hydration, no pore clogging.",
    rating: 4.5,
    reviews: 344,
    stock: "in",
    badge: "Vegan",
    size: "50ml",
    skinType: "Normal to combination skin",
  },
  {
    id: 32,
    name: "My Clarins Clear-Out Blackhead Expert Stick",
    brand: "My Clarins",
    category: "Skincare",
    price: 22000,
    originalPrice: 27000,
    description: "Vegan targeted blackhead and blemish stick. Unclogs pores, reduces shine and keeps skin clear.",
    rating: 4.4,
    reviews: 512,
    stock: "in",
    badge: "Vegan",
    size: "3g",
    skinType: "Oily to combination skin",
  },
];

export default products;